---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://grafana.observability:80 # Grafana URL
    adminPassword:
      name: grafana-secret
      key: adminPass
    adminUser:
      name: grafana-secret
      key: adminUser
