apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: external-folder
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "External"
  uid: "external-folder"
