---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: external-alertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  name: alertmanager
  type: prometheus-alertmanager

  settings:
    url: "http://alertmanager-operated.observability.svc.cluster.local:9093"
