apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
  namespace: kube-system
stringData:
  BW_CLIENTID: ENC[AES256_GCM,data:MUKNDovNjSEgAvhWeGwYwAxhYJyf5R8/tqO8lUmY+9q0gwECyxMmXy0=,iv:swMgisR1Edpb/m1o1m3/WKilOi2509RGtCiQDZR2Lh4=,tag:ha7AZv9BwiG8l/9MNn72sQ==,type:str]
  BW_CLIENTSECRET: ENC[AES256_GCM,data:y6nSGVifJSgk8SxxYp9EEK/RYmiF5uAJRQKsQFHt,iv:aShhn06ZhcJi0AmSsthmeBPIvVWUcGeacN4Xw89t2gk=,tag:s/26NYIclcaNpp/Bn+HIUw==,type:str]
  BW_HOST: ENC[AES256_GCM,data:75JPzjKN8Fqaq5wlTKIC0Kt/KPGtUqs=,iv:mpIeV7Xas0QPx0Pe5vHEKqWdcXuqxY57qxfV710YuNs=,tag:bFDFpSPAoSgvvdAkFJMwVQ==,type:str]
  BW_PASSWORD: ENC[AES256_GCM,data:LFqSfg9EScgaIunOxfI=,iv:wCYkETUWu0iKUTQO9NgCEnkZsi7lYLbfYAmQgNCA8t0=,tag:1ZM7B9XnVwX7ygw+6TDrhg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySzRwdk4yQVo0M3N3UWY4
        RWk3VjZsMjEzU0N0RVVJVmhrNFViRXJ2WG1RCnNOUTNOUkkrNkpPVkpyRUVIRHd1
        YmgveEMyTGZxejIyTERuOUEzbnNmdDQKLS0tIFRnMUpBbEY5MXExcHh5c3Nmamhj
        Y0Z5TUhsaC91WVl0ZjFSS3JVMUVwTlUKrTrFqPJkPyXy4PzyCs59TVGdeJq2FA27
        Qv5HnfsGBYx/wcMIcU3KwV3VnnbDX0gcX8DaRFoQ0JYlsLzfd8jQNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-11-12T13:23:05Z"
  mac: ENC[AES256_GCM,data:4ZtSXqdBM9M5QHyn9fnDNsjU+RFkdGLBlo0OI5Bfu08rv9KB3Dq0M2hbB0m7rtGoXi5i/yggctzYCKK8RNAWEX+rDauQtA5LXV9K3v0lTGJMSqxuHgKRUyjG8nFGJfgx94NG82qCIeukZRNCbSjANUa1Nok27FPfEOStTOtQals=,iv:o/CYWXawNnKSfWwCaCJ4/h/PFYaFk0YOO6punA9KXMs=,tag:J06bNent1PykzgGPJxXMTA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
