---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
data:
  config.json: |
    {
      "mcpServers": {
        "grafana": {
          "type": "sse",
          "url": "http://mcp-grafana.default.svc.cluster.local:8000/sse"
        }
      }
    }
