---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
data:
  config.json: |
    {
      "mcpServers": {
        "grafana": {
          "type": "streamable-http",
          "url": "http://mcp-grafana.default.svc.cluster.local:8000/mcp"
        }
      }
    }
