---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
data:
  config.json: |
    {
      "mcpServers": {
        "time": {
          "type": "sse",
          "url": "http://mcp-time.default.svc.cluster.local:8002/mcp/sse"
        }
      }
    }
