---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mcpo-secret
spec:
  refreshInterval: 15m
  target:
    deletionPolicy: Delete
    template:
      data:
        FIREFLY_PAT: "{{ .FIREFLY_PAT }}"
        CONTEXT7_API_KEY: "{{ .CONTEXT7_API_KEY }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
      # templateFrom:
      #   - configMap:
      #       name: mcpo-config-tpl
      #       items:
      #         - key: config.yaml
  data:
    - secretKey: FIREFLY_PAT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: pat
    - secretKey: CONTEXT7_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f70e550d-01b3-4ab7-8329-339461d33741
        property: context7-api-key
    - secretKey: GITHUB_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b67e4583-a622-4cf2-a172-58ee67c703da
        property: github-mcp
