---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocis
  namespace: media
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: ocis
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
  path: ./kubernetes/apps/media/ocis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 24h
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: ocis
      VOLSYNC_CLAIM: ocis-data
      VOLSYNC_CAPACITY: 15Gi
      SUBDOMAIN: drive
  components:
    - ../../../../components/volsync-no-r2
