---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unbound
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    disableSchemaValidation: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: v0.1.0
        env:
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: external-dns-opnsense-secret
                key: OPNSENSE_API_SECRET
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-opnsense-secret
                key: OPNSENSE_API_KEY
          - name: OPNSENSE_HOST
            valueFrom:
              secretKeyRef:
                name: external-dns-opnsense-secret
                key: OPNSENSE_HOST
          - name: OPNSENSE_SKIP_TLS_VERIFY
            value: "true"
          - name: LOG_LEVEL
            value: "info"
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    # triggerLoopOnEvent: true
    logLevel: debug
    policy: sync
    extraArgs:
      - --webhook-provider-url="http://0.0.0.0:8080"
    #   - --gateway-name=envoy-internal
    registry: noop
    sources:
      # - crd
      #- ingress
      - gateway-grpcroute
      - gateway-httproute
      - gateway-tlsroute
      - gateway-udproute
      - gateway-tcproute
      # - service

    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - cloudjur.com

    serviceMonitor:
      enabled: true
    podAnnotations:
      reloader.stakater.com/auto: "true"
