---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname mcp-grafana
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/default/mcp-servers/mcp-grafana"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  # components:
  #   - ../../../../components/gatus/guarded
  # postBuild:
  #   substitute:
  #     APP: *appname
  #     APP_UID: "1000"
  #     APP_GID: "1000"
  #     VOLSYNC_CAPACITY: 5Gi
