---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app opencloud
  namespace: media
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync-no-r2
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
  interval: 30m
  path: ./kubernetes/apps/media/opencloud/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: opencloud-data
      VOLSYNC_CAPACITY: 20Gi
      SUBDOMAIN: drive
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  retryInterval: 1m
  timeout: 5m
