---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pve
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - pve.cloudjur.com
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: pve
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: pve
spec:
  endpoints:
    - ip:
        address: 192.168.1.10
        port: 8006
    - ip:
        address: 10.10.30.10
        port: 8006
  tls:
    insecureSkipVerify: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: pve
spec:
  mergeType: StrategicMerge
  loadBalancer:
    consistentHash:
      type: SourceIP
    type: ConsistentHash
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: pve

