# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: &app pve
#   namespace: network
#   labels:
#     app.kubernetes.io/name: *app
#     app.kubernetes.io/instance: *app
# spec:
#   type: ClusterIP
#   clusterIP: None
#   ports:
#     - name: http
#       port: &port 8006
#       protocol: TCP
#       targetPort: *port
# ---
# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#   name: &app pve
#   namespace: network
#   labels:
#     kubernetes.io/service-name: *app
# addressType: IPv4
# ports:
#   - name: http
#     appProtocol: http
#     protocol: TCP
#     port: 8006
# endpoints:
#   - addresses:
#       - "10.10.30.1"
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: pve
#   namespace: network
#   labels:
#     app.kubernetes.io/name: pve
#     app.kubernetes.io/instance: pve
# spec:
#   parentRefs:
#     - name: envoy-internal
#       namespace: network
#       sectionName: https
#   hostnames:
#     - pve.cloudjur.com
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: pve
#           port: 8006

# apiVersion: v1
# kind: Service
# metadata:
#   name: proxmox
# spec:
#   ports:
#     - name: https
#       protocol: TCP
#       port: 8006
#       targetPort: 8006
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: proxmox
#   namespace: network
#   labels:
#     app.kubernetes.io/name: proxmox
#     app.kubernetes.io/instance: proxmox
# spec:
#   parentRefs:
#     - name: envoy-internal
#       namespace: network
#       sectionName: https
#   hostnames:
#     - pve.cloudjur.com
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: proxmox
#           port: 8006
# ---
# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#   name: proxmox
#   labels:
#     kubernetes.io/service-name: proxmox
#     endpointslice.kubernetes.io/managed-by: cluster-admins
# addressType: IPv4
# ports:
#   - name: https
#     protocol: TCP
#     port: 8006
# endpoints:
#   - addresses:
#       - 10.10.30.10
#       - 192.168.1.10
#     conditions:
#       ready: true # https://github.com/argoproj/argo-cd/issues/15554
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: proxmox
# spec:
#   ports:
#     - name: https
#       protocol: TCP
#       port: 443
#       appProtocol: kubernetes.io/h2c
#       targetPort: 8006
# ---
# apiVersion: gateway.networking.k8s.io/v1alpha2
# kind: TLSRoute
# metadata:
#   name: proxmox
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: 10.10.30.25
# spec:
#   parentRefs:
#     - {name: envoy-internal, namespace: network, port: 6443}
#   hostnames: [pve.cloudjur.com]
#   rules:
#     - backendRefs: [{name: proxmox, port: 443}]

---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pve
  # annotations:
  #   gatus.home-operations.com/enabled: "false"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  hostnames:
    - pve.cloudjur.com
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: pve
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: pve
spec:
  endpoints:
    - ip:
        address: 192.168.1.10
        port: 8006
    - ip:
        address: 10.10.30.10
        port: 8006
  tls:
    insecureSkipVerify: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: pve
spec:
  mergeType: StrategicMerge
  loadBalancer:
    consistentHash:
      type: SourceIP
    type: ConsistentHash
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: pve
