---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        QUI__SESSION_SECRET: "{{ .QUI__SESSION_SECRET }}"
  data:
    - secretKey: QUI__SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d33214f7-7292-4774-afdd-f53630fb8d03
        property: QUI__SESSION_SECRET
