---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-secret
spec:
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_CLIENT_SECRET }}"
        # Admin User
        adminUser: "{{ .username }}"
        adminPass: "{{ .password }}"
        # GF_SECURITY_ADMIN_PASSWORD: "{{ .password }}"
        # GF_DATABASE_NAME: &dbName grafana
        # GF_DATABASE_HOST: postgres-rw.database.svc.cluster.local:5432
        # GF_DATABASE_USER: &dbUser "{{ .GRAFANA_POSTGRES_USER }}"
        # GF_DATABASE_PASSWORD: &dbPass "{{ .GRAFANA_POSTGRES_PASS }}"
        # GF_DATABASE_SSL_MODE: disable
        # GF_DATABASE_TYPE: postgres
        # INIT_POSTGRES_DBNAME: *dbName
        # INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        # INIT_POSTGRES_USER: *dbUser
        # INIT_POSTGRES_PASS: *dbPass
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: password
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    - secretKey: GRAFANA_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: GRAFANA_CLIENT_ID
    - secretKey: GRAFANA_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: GRAFANA_CLIENT_SECRET
    - secretKey: GRAFANA_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: pg_user
    - secretKey: GRAFANA_POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: pg_password
---
# ExternalSecret to populate the grafana-datasources Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-datasources-es
spec:
  refreshInterval: 15m
  target:
    name: grafana-datasources
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana_datasource: "true"
      data:
        # Grafana datasource configuration using templated values
        grafana-datasource.yaml: |-
          apiVersion: 1
          datasources:
            - name: fly-io-prometheus
              type: prometheus
              uid: prometheus
              access: proxy
              url: "{{ .fly_io_prometheus_url }}"
              httpHeaderName1: Authorization
              secureJsonData:
                httpHeaderValue1: "{{ .fly_io_readonly_token }}"
  # Map remote values into the created Secret as keys
  data:
    - secretKey: fly_io_readonly_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: fly_io_readonly_token
    - secretKey: fly_io_prometheus_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: fly_io_prometheus_url
