---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name booklore-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: booklore_mariadb_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 124108a5-0598-4486-948e-cc37eea060e7
        property: mariadb_password
    - secretKey: booklore_mariadb_root_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 124108a5-0598-4486-948e-cc37eea060e7
        property: mariadb_root_password
