---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly
  namespace: default
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: firefly
  interval: 10m
  path: ./kubernetes/apps/default/firefly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
  postBuild:
    substitute:
      APP: firefly
      SUBDOMAIN: money
  components:
    - ../../../../components/volsync
