---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: pgo-s3-creds
spec:
  externalSecretName: pgo-s3-creds

  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden-fields

    target:
      name: pgo-s3-creds
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          s3.conf: |
            [global]
            repo1-s3-key=crunchy-postgres
            repo1-s3-key-secret={{ .owner_access_key }}

    data:
      - secretKey: owner_access_key
        sourceRef:
          storeRef:
            name: bitwarden-fields
            kind: ClusterSecretStore
        remoteRef:
          key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
          property: owner_access_key
      - secretKey: owner_secret_key
        sourceRef:
          storeRef:
            name: bitwarden-fields
            kind: ClusterSecretStore
        remoteRef:
          key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
          property: owner_secret_key
### SMTP
