---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name syncthing-secret
spec:
  refreshInterval: 15m
  target:
    name: *name
    template:
      data:
        SYNCTHING_API_KEY: "{{ .SYNCTHING_API_KEY }}"
  data:
    - secretKey: SYNCTHING_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 71d68362-c60b-4426-b746-fb871452bd20
        property: api_key
