---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-downloader
  namespace: downloads
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: calibre-downloader
  path: ./kubernetes/apps/downloads/calibre-downloader/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: calibre-downloader
      SUBDOMAIN: dl-books
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  wait: false
  interval: 24h
  timeout: 5m
  components:
    - ../../../../components/keda/nfs-scaler
