---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webhook
  namespace: downloads
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: webhook
  interval: 1h # interval: 1h
  path: ./kubernetes/apps/downloads/webhook/app
  postBuild:
    substitute:
      APP: webhook
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
