---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neko-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: |-
          {{ .root_username }}
        NEKO_MEMBER_MULTIUSER_USER_PASSWORD: |-
          {{ .root_password }}
  refreshInterval: 15m
  data:
    - secretKey: root_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4eaceeba-1441-4869-9b1f-9a8178727ef9
        property: admin_password
    - secretKey: root_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4eaceeba-1441-4869-9b1f-9a8178727ef9
        property: password
