---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tf-controller-sops
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: tf-controller-sops-secret
    template:
      engineVersion: v2
      data:
        keys.txt: "{{ .SOPS_AGE_KEY }}"
  data:
    - secretKey: SOPS_AGE_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb424eb9-ca32-4608-93ef-63e28c3f531e
        property: age_key # Replaced property with age_key based on common pattern
