---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/chaijunkin/manifests/terraform
  ref:
    tag: main
