---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-not
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-not",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth2",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "10.10.32.254/24",
                "gateway": "10.10.32.1"
              }
            ],
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.10.32.1" }
            ]
          }
        }
      ]
    }
