---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name headlamp-secret
spec:
  target:
    name: *name
    template:
      data:
        # OIDC configuration
        OIDC_ISSUER_URL: "https://auth.cloudjur.com/application/o/headlamp/"
        OIDC_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .HEADLAMP_CLIENT_SECRET }}"
        OIDC_SCOPES: "openid email profile"
        # OIDC_VALIDATOR_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
        # OIDC_VALIDATOR_ISSUER_URL: "https://auth.cloudjur.com/application/o/headlamp/"
  data:
    - secretKey: HEADLAMP_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 153f8e3f-cf1d-4ac6-af96-b934baab3bc5
        property: client_id
    - secretKey: HEADLAMP_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 153f8e3f-cf1d-4ac6-af96-b934baab3bc5
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-ca-cert
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: headlamp-ca-cert
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.crt
      remoteRef:
        key: cloudjur-com-tls
        property: tls.crt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headlamp-external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-external-secrets
subjects:
  - kind: ServiceAccount
    name: headlamp-external-secrets
    namespace: flux-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-store
spec:
  provider:
    kubernetes:
      server:
        url: https://kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: headlamp-external-secrets
      remoteNamespace: network
